---
deployment:
  tasks:
    - /bin/echo "=== Deploying franchise-frontend ==="

    - /bin/npm install
    - /bin/npm run build

    - /bin/mkdir -p /home/fuma/public_html/fumaretail

    - /bin/rsync -av --delete build/ /home/fuma/public_html/fumaretail/

    - /bin/echo "=== franchise-frontend deploy complete ==="
